### ISSUE TITLE
> implying code is solid

### ISSUE THREAD

**Issue by arecker** [LoremIpsumMysterium/FactaNonVerba#1]
![](http://i3.kym-cdn.com/photos/images/original/000/243/837/f7e.gif)

**Comment by LoremIpsumMysterium** [comment]
There is practically no code at all. Ergo ipsum facto, it is solid. SOLID+++ even. A mongoloid couldn't even mess this up. Furthermore, meow. Case closed.

**Comment by arecker** [comment]
> Ergo

That gives me license to refactor your face.

**Comment by arecker** [comment]
pls sir what is join?
